# Read the Docs 配置文件版本（必填，当前固定为 2）
version: 2
sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py
# ------------------------------
# 1. 构建环境配置（核心：指定 macOS 系统）
# ------------------------------
build:
  # 操作系统：明确指定为 macOS（可选值：ubuntu-22.04, macos-12, windows-2022）
  os: ubuntu-22.04
  # 构建工具：默认使用 "sphinx"（文档生成工具，若用 MkDocs 需改为 "mkdocs"）
  tools:
    # Python 版本：指定项目使用的 Python 版本（macOS 预装 Python，但建议显式指定避免兼容问题）
    python: "3.11"

